// Process Image File
// Generated by CANopen Architect Mini 8.25.5874 on 10/05/2021 05:45:56 PM
// Generated from project C:\Users\navin\Desktop\CanOpen\ManagerWorking.caxe
// Generated from EDS 'CANopenNXPSDK_Mgr' 04-27-2021 07:20PM by Pf
// Use with MicroCANopen Plus CANopen stack
// For more information visit www.esacademy.com and www.microcanopen.com

// Check for warnings below before using this file

#ifndef _PIMGH_
#define _PIMGH_

// EDS configuration usage
// 1 = configuration was used when this file was generated
#define EDSCONFIGURATION_ALL_ENTRIES 1

// EDS group usage
// 1 = group was used when this file was generated

// set to 1 to use this stack config
#define AUTO_GENERATED_STACK_CONFIG 1

#if (AUTO_GENERATED_STACK_CONFIG == 1)
// stack configuration

// if no stack version defined then assume version 5.xx
#ifndef _MCOPVERSION_
#define _MCOPVERSION_ 5
#endif

// Maximum number of receive PDOs
#define NR_OF_RPDOS       2

// Maximum number of transmit PDOs
#define NR_OF_TPDOS       2

// Default Node ID of this node
#if _MCOPVERSION_ >= 6
#define NODEID_DCF         0x01
#define DEFAULT_EMCY_COBID 0x00000080L + NODEID_DCF
#else
#define NODE_ID            0x01
#define DEFAULT_EMCY_COBID 0x00000080L + NODE_ID
#endif

// device type
#define OD_DEVICE_TYPE    0x00000000L

// Identity Object data [1018]
// Note: the values in Device -> Information are not used for this piece of code,
// only the values in [1018] are used
#define OD_VENDOR_ID      0xAF0002DCL
#define OD_PRODUCT_CODE   0xC0DE0001L
#define OD_REVISION       0x20201014L
#define OD_SERIAL_NUMBER  0x00000000L

// Specify the default heartbeat here
#define DEFAULT_HEARTBEAT 333

// Defines the maximum number of heartbeat consumers
#define NR_OF_HB_CONSUMER 10

// Defines the maximum number of emergency consumers
#define NR_OF_EMCY_CONSUMERS 0

// Defines the emergency inhibit time (x100us)
#define EMCY_INHIBIT_TIME 100

#endif // AUTO_GENERATED_STACK_CONFIG == 1

// [6200,01] Unsigned8
#define P620001_DigOutput8_1 0x00000000
#define PDigOutput8_1_620001 P620001_DigOutput8_1
#define P620001 P620001_DigOutput8_1
#define P0x62000x01 P620001_DigOutput8_1
// The uppercase versions are deprecated
#define P620001_DIGOUTPUT8_1 P620001_DigOutput8_1
#define PDIGOUTPUT8_1_620001 P620001_DigOutput8_1
// [6200,02] Unsigned8
#define P620002_DigOutput8_2 0x00000001
#define PDigOutput8_2_620002 P620002_DigOutput8_2
#define P620002 P620002_DigOutput8_2
#define P0x62000x02 P620002_DigOutput8_2
// The uppercase versions are deprecated
#define P620002_DIGOUTPUT8_2 P620002_DigOutput8_2
#define PDIGOUTPUT8_2_620002 P620002_DigOutput8_2
// [6200,03] Unsigned8
#define P620003_DigOutput8_3 0x00000002
#define PDigOutput8_3_620003 P620003_DigOutput8_3
#define P620003 P620003_DigOutput8_3
#define P0x62000x03 P620003_DigOutput8_3
// The uppercase versions are deprecated
#define P620003_DIGOUTPUT8_3 P620003_DigOutput8_3
#define PDIGOUTPUT8_3_620003 P620003_DigOutput8_3
// [6200,04] Unsigned8
#define P620004_DigOutput8_4 0x00000003
#define PDigOutput8_4_620004 P620004_DigOutput8_4
#define P620004 P620004_DigOutput8_4
#define P0x62000x04 P620004_DigOutput8_4
// The uppercase versions are deprecated
#define P620004_DIGOUTPUT8_4 P620004_DigOutput8_4
#define PDIGOUTPUT8_4_620004 P620004_DigOutput8_4
// [6411,01] Integer16
#define P641101_AnalogOutput16_1 0x00000004
#define PAnalogOutput16_1_641101 P641101_AnalogOutput16_1
#define P641101 P641101_AnalogOutput16_1
#define P0x64110x01 P641101_AnalogOutput16_1
// The uppercase versions are deprecated
#define P641101_ANALOGOUTPUT16_1 P641101_AnalogOutput16_1
#define PANALOGOUTPUT16_1_641101 P641101_AnalogOutput16_1
// [6411,02] Integer16
#define P641102_AnalogOutput16_2 0x00000006
#define PAnalogOutput16_2_641102 P641102_AnalogOutput16_2
#define P641102 P641102_AnalogOutput16_2
#define P0x64110x02 P641102_AnalogOutput16_2
// The uppercase versions are deprecated
#define P641102_ANALOGOUTPUT16_2 P641102_AnalogOutput16_2
#define PANALOGOUTPUT16_2_641102 P641102_AnalogOutput16_2
// [6000,01] Unsigned8
#define P600001_VC_Command 0x00000008
#define PVC_Command_600001 P600001_VC_Command
#define P600001 P600001_VC_Command
#define P0x60000x01 P600001_VC_Command
// The uppercase versions are deprecated
#define P600001_VC_COMMAND P600001_VC_Command
#define PVC_COMMAND_600001 P600001_VC_Command
// [6000,02] Unsigned8
#define P600002_VC_Accuracy 0x00000009
#define PVC_Accuracy_600002 P600002_VC_Accuracy
#define P600002 P600002_VC_Accuracy
#define P0x60000x02 P600002_VC_Accuracy
// The uppercase versions are deprecated
#define P600002_VC_ACCURACY P600002_VC_Accuracy
#define PVC_ACCURACY_600002 P600002_VC_Accuracy
// [6000,03] Unsigned8
#define P600003_DigInput8_3 0x0000000A
#define PDigInput8_3_600003 P600003_DigInput8_3
#define P600003 P600003_DigInput8_3
#define P0x60000x03 P600003_DigInput8_3
// The uppercase versions are deprecated
#define P600003_DIGINPUT8_3 P600003_DigInput8_3
#define PDIGINPUT8_3_600003 P600003_DigInput8_3
// [6000,04] Unsigned8
#define P600004_DigInput8_4 0x0000000B
#define PDigInput8_4_600004 P600004_DigInput8_4
#define P600004 P600004_DigInput8_4
#define P0x60000x04 P600004_DigInput8_4
// The uppercase versions are deprecated
#define P600004_DIGINPUT8_4 P600004_DigInput8_4
#define PDIGINPUT8_4_600004 P600004_DigInput8_4
// [6401,01] Integer16
#define P640101_AnalogInput16_1 0x0000000C
#define PAnalogInput16_1_640101 P640101_AnalogInput16_1
#define P640101 P640101_AnalogInput16_1
#define P0x64010x01 P640101_AnalogInput16_1
// The uppercase versions are deprecated
#define P640101_ANALOGINPUT16_1 P640101_AnalogInput16_1
#define PANALOGINPUT16_1_640101 P640101_AnalogInput16_1
// [6401,02] Integer16
#define P640102_AnalogInput16_2 0x0000000E
#define PAnalogInput16_2_640102 P640102_AnalogInput16_2
#define P640102 P640102_AnalogInput16_2
#define P0x64010x02 P640102_AnalogInput16_2
// The uppercase versions are deprecated
#define P640102_ANALOGINPUT16_2 P640102_AnalogInput16_2
#define PANALOGINPUT16_2_640102 P640102_AnalogInput16_2
// [1000,00] Unsigned32
#define P100000_Device_Type 0x00000010
#define PDevice_Type_100000 P100000_Device_Type
#define P100000 P100000_Device_Type
#define P0x10000x00 P100000_Device_Type
// The uppercase versions are deprecated
#define P100000_DEVICE_TYPE P100000_Device_Type
#define PDEVICE_TYPE_100000 P100000_Device_Type
// [1001,00] Unsigned8
#define P100100_Error_Register 0x00000014
#define PError_Register_100100 P100100_Error_Register
#define P100100 P100100_Error_Register
#define P0x10010x00 P100100_Error_Register
// The uppercase versions are deprecated
#define P100100_ERROR_REGISTER P100100_Error_Register
#define PERROR_REGISTER_100100 P100100_Error_Register
// [1005,00] Unsigned32
#define P100500_COB_ID_SYNC 0x00000015
#define PCOB_ID_SYNC_100500 P100500_COB_ID_SYNC
#define P100500 P100500_COB_ID_SYNC
#define P0x10050x00 P100500_COB_ID_SYNC
// [1006,00] Unsigned32
#define P100600_SYNC_Communication_cycle_time 0x00000019
#define PSYNC_Communication_cycle_time_100600 P100600_SYNC_Communication_cycle_time
#define P100600 P100600_SYNC_Communication_cycle_time
#define P0x10060x00 P100600_SYNC_Communication_cycle_time
// The uppercase versions are deprecated
#define P100600_SYNC_COMMUNICATION_CYCLE_TIME P100600_SYNC_Communication_cycle_time
#define PSYNC_COMMUNICATION_CYCLE_TIME_100600 P100600_SYNC_Communication_cycle_time
// [1008,00] VisibleString
#define P100800_Manufacturer_Device_Name 0x0000001D
#define PManufacturer_Device_Name_100800 P100800_Manufacturer_Device_Name
#define P100800 P100800_Manufacturer_Device_Name
#define P0x10080x00 P100800_Manufacturer_Device_Name
// The uppercase versions are deprecated
#define P100800_MANUFACTURER_DEVICE_NAME P100800_Manufacturer_Device_Name
#define PMANUFACTURER_DEVICE_NAME_100800 P100800_Manufacturer_Device_Name
// [1010,00] Unsigned8
#define P101000_Highest_Subindex 0x0000003D
#define PHighest_Subindex_101000 P101000_Highest_Subindex
#define P101000 P101000_Highest_Subindex
#define P0x10100x00 P101000_Highest_Subindex
// The uppercase versions are deprecated
#define P101000_HIGHEST_SUBINDEX P101000_Highest_Subindex
#define PHIGHEST_SUBINDEX_101000 P101000_Highest_Subindex
// [1010,01] Unsigned32
#define P101001_Save_All_Parameters 0x0000003E
#define PSave_All_Parameters_101001 P101001_Save_All_Parameters
#define P101001 P101001_Save_All_Parameters
#define P0x10100x01 P101001_Save_All_Parameters
// The uppercase versions are deprecated
#define P101001_SAVE_ALL_PARAMETERS P101001_Save_All_Parameters
#define PSAVE_ALL_PARAMETERS_101001 P101001_Save_All_Parameters
// [1010,02] Unsigned32
#define P101002_Save_Communication_Parameters 0x00000042
#define PSave_Communication_Parameters_101002 P101002_Save_Communication_Parameters
#define P101002 P101002_Save_Communication_Parameters
#define P0x10100x02 P101002_Save_Communication_Parameters
// The uppercase versions are deprecated
#define P101002_SAVE_COMMUNICATION_PARAMETERS P101002_Save_Communication_Parameters
#define PSAVE_COMMUNICATION_PARAMETERS_101002 P101002_Save_Communication_Parameters
// [1010,03] Unsigned32
#define P101003_Save_Application_Parameters 0x00000046
#define PSave_Application_Parameters_101003 P101003_Save_Application_Parameters
#define P101003 P101003_Save_Application_Parameters
#define P0x10100x03 P101003_Save_Application_Parameters
// The uppercase versions are deprecated
#define P101003_SAVE_APPLICATION_PARAMETERS P101003_Save_Application_Parameters
#define PSAVE_APPLICATION_PARAMETERS_101003 P101003_Save_Application_Parameters
// [1010,04] Unsigned32
#define P101004_Save_Manufacturer_Parameters 0x0000004A
#define PSave_Manufacturer_Parameters_101004 P101004_Save_Manufacturer_Parameters
#define P101004 P101004_Save_Manufacturer_Parameters
#define P0x10100x04 P101004_Save_Manufacturer_Parameters
// The uppercase versions are deprecated
#define P101004_SAVE_MANUFACTURER_PARAMETERS P101004_Save_Manufacturer_Parameters
#define PSAVE_MANUFACTURER_PARAMETERS_101004 P101004_Save_Manufacturer_Parameters
// [1014,00] Unsigned32
#define P101400_COB_ID_EMCY 0x0000004E
#define PCOB_ID_EMCY_101400 P101400_COB_ID_EMCY
#define P101400 P101400_COB_ID_EMCY
#define P0x10140x00 P101400_COB_ID_EMCY
// [1016,01] Unsigned32
#define P101601_Consumer_HB_Time 0x00000052
#define PConsumer_HB_Time_101601 P101601_Consumer_HB_Time
#define P101601 P101601_Consumer_HB_Time
#define P0x10160x01 P101601_Consumer_HB_Time
// The uppercase versions are deprecated
#define P101601_CONSUMER_HB_TIME P101601_Consumer_HB_Time
#define PCONSUMER_HB_TIME_101601 P101601_Consumer_HB_Time
// [1016,02] Unsigned32
#define P101602_Consumer_HB_Time 0x00000056
#define PConsumer_HB_Time_101602 P101602_Consumer_HB_Time
#define P101602 P101602_Consumer_HB_Time
#define P0x10160x02 P101602_Consumer_HB_Time
// The uppercase versions are deprecated
#define P101602_CONSUMER_HB_TIME P101602_Consumer_HB_Time
#define PCONSUMER_HB_TIME_101602 P101602_Consumer_HB_Time
// [1016,03] Unsigned32
#define P101603_Consumer_HB_Time 0x0000005A
#define PConsumer_HB_Time_101603 P101603_Consumer_HB_Time
#define P101603 P101603_Consumer_HB_Time
#define P0x10160x03 P101603_Consumer_HB_Time
// The uppercase versions are deprecated
#define P101603_CONSUMER_HB_TIME P101603_Consumer_HB_Time
#define PCONSUMER_HB_TIME_101603 P101603_Consumer_HB_Time
// [1016,04] Unsigned32
#define P101604_Consumer_HB_Time 0x0000005E
#define PConsumer_HB_Time_101604 P101604_Consumer_HB_Time
#define P101604 P101604_Consumer_HB_Time
#define P0x10160x04 P101604_Consumer_HB_Time
// The uppercase versions are deprecated
#define P101604_CONSUMER_HB_TIME P101604_Consumer_HB_Time
#define PCONSUMER_HB_TIME_101604 P101604_Consumer_HB_Time
// [1016,05] Unsigned32
#define P101605_Consumer_HB_Time 0x00000062
#define PConsumer_HB_Time_101605 P101605_Consumer_HB_Time
#define P101605 P101605_Consumer_HB_Time
#define P0x10160x05 P101605_Consumer_HB_Time
// The uppercase versions are deprecated
#define P101605_CONSUMER_HB_TIME P101605_Consumer_HB_Time
#define PCONSUMER_HB_TIME_101605 P101605_Consumer_HB_Time
// [1016,06] Unsigned32
#define P101606_Consumer_HB_Time 0x00000066
#define PConsumer_HB_Time_101606 P101606_Consumer_HB_Time
#define P101606 P101606_Consumer_HB_Time
#define P0x10160x06 P101606_Consumer_HB_Time
// The uppercase versions are deprecated
#define P101606_CONSUMER_HB_TIME P101606_Consumer_HB_Time
#define PCONSUMER_HB_TIME_101606 P101606_Consumer_HB_Time
// [1016,07] Unsigned32
#define P101607_Consumer_HB_Time 0x0000006A
#define PConsumer_HB_Time_101607 P101607_Consumer_HB_Time
#define P101607 P101607_Consumer_HB_Time
#define P0x10160x07 P101607_Consumer_HB_Time
// The uppercase versions are deprecated
#define P101607_CONSUMER_HB_TIME P101607_Consumer_HB_Time
#define PCONSUMER_HB_TIME_101607 P101607_Consumer_HB_Time
// [1016,08] Unsigned32
#define P101608_Consumer_HB_Time 0x0000006E
#define PConsumer_HB_Time_101608 P101608_Consumer_HB_Time
#define P101608 P101608_Consumer_HB_Time
#define P0x10160x08 P101608_Consumer_HB_Time
// The uppercase versions are deprecated
#define P101608_CONSUMER_HB_TIME P101608_Consumer_HB_Time
#define PCONSUMER_HB_TIME_101608 P101608_Consumer_HB_Time
// [1016,09] Unsigned32
#define P101609_Consumer_HB_Time 0x00000072
#define PConsumer_HB_Time_101609 P101609_Consumer_HB_Time
#define P101609 P101609_Consumer_HB_Time
#define P0x10160x09 P101609_Consumer_HB_Time
// The uppercase versions are deprecated
#define P101609_CONSUMER_HB_TIME P101609_Consumer_HB_Time
#define PCONSUMER_HB_TIME_101609 P101609_Consumer_HB_Time
// [1016,0A] Unsigned32
#define P10160A_Consumer_HB_Time 0x00000076
#define PConsumer_HB_Time_10160A P10160A_Consumer_HB_Time
#define P10160A P10160A_Consumer_HB_Time
#define P0x10160x0A P10160A_Consumer_HB_Time
// The uppercase versions are deprecated
#define P10160A_CONSUMER_HB_TIME P10160A_Consumer_HB_Time
#define PCONSUMER_HB_TIME_10160A P10160A_Consumer_HB_Time
// [1017,00] Unsigned16
#define P101700_Producer_Heartbeat_Time 0x0000007A
#define PProducer_Heartbeat_Time_101700 P101700_Producer_Heartbeat_Time
#define P101700 P101700_Producer_Heartbeat_Time
#define P0x10170x00 P101700_Producer_Heartbeat_Time
// The uppercase versions are deprecated
#define P101700_PRODUCER_HEARTBEAT_TIME P101700_Producer_Heartbeat_Time
#define PPRODUCER_HEARTBEAT_TIME_101700 P101700_Producer_Heartbeat_Time
// [1019,00] Unsigned8
#define P101900_SYNC_counter_overflow_value 0x0000007C
#define PSYNC_counter_overflow_value_101900 P101900_SYNC_counter_overflow_value
#define P101900 P101900_SYNC_counter_overflow_value
#define P0x10190x00 P101900_SYNC_counter_overflow_value
// The uppercase versions are deprecated
#define P101900_SYNC_COUNTER_OVERFLOW_VALUE P101900_SYNC_counter_overflow_value
#define PSYNC_COUNTER_OVERFLOW_VALUE_101900 P101900_SYNC_counter_overflow_value
// [1400,00] Unsigned8
#define P140000_Highest_Subindex 0x0000007D
#define PHighest_Subindex_140000 P140000_Highest_Subindex
#define P140000 P140000_Highest_Subindex
#define P0x14000x00 P140000_Highest_Subindex
// The uppercase versions are deprecated
#define P140000_HIGHEST_SUBINDEX P140000_Highest_Subindex
#define PHIGHEST_SUBINDEX_140000 P140000_Highest_Subindex
// [1400,01] Unsigned32
#define P140001_COB_ID 0x0000007E
#define PCOB_ID_140001 P140001_COB_ID
#define P140001 P140001_COB_ID
#define P0x14000x01 P140001_COB_ID
// [1400,02] Unsigned8
#define P140002_Transmission_Type 0x00000082
#define PTransmission_Type_140002 P140002_Transmission_Type
#define P140002 P140002_Transmission_Type
#define P0x14000x02 P140002_Transmission_Type
// The uppercase versions are deprecated
#define P140002_TRANSMISSION_TYPE P140002_Transmission_Type
#define PTRANSMISSION_TYPE_140002 P140002_Transmission_Type
// [1401,00] Unsigned8
#define P140100_Highest_Subindex 0x00000083
#define PHighest_Subindex_140100 P140100_Highest_Subindex
#define P140100 P140100_Highest_Subindex
#define P0x14010x00 P140100_Highest_Subindex
// The uppercase versions are deprecated
#define P140100_HIGHEST_SUBINDEX P140100_Highest_Subindex
#define PHIGHEST_SUBINDEX_140100 P140100_Highest_Subindex
// [1401,01] Unsigned32
#define P140101_COB_ID 0x00000084
#define PCOB_ID_140101 P140101_COB_ID
#define P140101 P140101_COB_ID
#define P0x14010x01 P140101_COB_ID
// [1401,02] Unsigned8
#define P140102_Transmission_Type 0x00000088
#define PTransmission_Type_140102 P140102_Transmission_Type
#define P140102 P140102_Transmission_Type
#define P0x14010x02 P140102_Transmission_Type
// The uppercase versions are deprecated
#define P140102_TRANSMISSION_TYPE P140102_Transmission_Type
#define PTRANSMISSION_TYPE_140102 P140102_Transmission_Type
// [1800,01] Unsigned32
#define P180001_COB_ID 0x00000089
#define PCOB_ID_180001 P180001_COB_ID
#define P180001 P180001_COB_ID
#define P0x18000x01 P180001_COB_ID
// [1800,02] Unsigned8
#define P180002_Transmission_Type 0x0000008D
#define PTransmission_Type_180002 P180002_Transmission_Type
#define P180002 P180002_Transmission_Type
#define P0x18000x02 P180002_Transmission_Type
// The uppercase versions are deprecated
#define P180002_TRANSMISSION_TYPE P180002_Transmission_Type
#define PTRANSMISSION_TYPE_180002 P180002_Transmission_Type
// [1800,03] Unsigned16
#define P180003_Inhibit_Time 0x0000008E
#define PInhibit_Time_180003 P180003_Inhibit_Time
#define P180003 P180003_Inhibit_Time
#define P0x18000x03 P180003_Inhibit_Time
// The uppercase versions are deprecated
#define P180003_INHIBIT_TIME P180003_Inhibit_Time
#define PINHIBIT_TIME_180003 P180003_Inhibit_Time
// [1800,05] Unsigned16
#define P180005_Event_Timer 0x00000090
#define PEvent_Timer_180005 P180005_Event_Timer
#define P180005 P180005_Event_Timer
#define P0x18000x05 P180005_Event_Timer
// The uppercase versions are deprecated
#define P180005_EVENT_TIMER P180005_Event_Timer
#define PEVENT_TIMER_180005 P180005_Event_Timer
// [1800,06] Unsigned8
#define P180006_Sync_Start_Value 0x00000092
#define PSync_Start_Value_180006 P180006_Sync_Start_Value
#define P180006 P180006_Sync_Start_Value
#define P0x18000x06 P180006_Sync_Start_Value
// The uppercase versions are deprecated
#define P180006_SYNC_START_VALUE P180006_Sync_Start_Value
#define PSYNC_START_VALUE_180006 P180006_Sync_Start_Value
// [1801,01] Unsigned32
#define P180101_COB_ID 0x00000093
#define PCOB_ID_180101 P180101_COB_ID
#define P180101 P180101_COB_ID
#define P0x18010x01 P180101_COB_ID
// [1801,02] Unsigned8
#define P180102_Transmission_Type 0x00000097
#define PTransmission_Type_180102 P180102_Transmission_Type
#define P180102 P180102_Transmission_Type
#define P0x18010x02 P180102_Transmission_Type
// The uppercase versions are deprecated
#define P180102_TRANSMISSION_TYPE P180102_Transmission_Type
#define PTRANSMISSION_TYPE_180102 P180102_Transmission_Type
// [1801,03] Unsigned16
#define P180103_Inhibit_Time 0x00000098
#define PInhibit_Time_180103 P180103_Inhibit_Time
#define P180103 P180103_Inhibit_Time
#define P0x18010x03 P180103_Inhibit_Time
// The uppercase versions are deprecated
#define P180103_INHIBIT_TIME P180103_Inhibit_Time
#define PINHIBIT_TIME_180103 P180103_Inhibit_Time
// [1801,05] Unsigned16
#define P180105_Event_Timer 0x0000009A
#define PEvent_Timer_180105 P180105_Event_Timer
#define P180105 P180105_Event_Timer
#define P0x18010x05 P180105_Event_Timer
// The uppercase versions are deprecated
#define P180105_EVENT_TIMER P180105_Event_Timer
#define PEVENT_TIMER_180105 P180105_Event_Timer
// [1801,06] Unsigned8
#define P180106_Sync_Start_Value 0x0000009C
#define PSync_Start_Value_180106 P180106_Sync_Start_Value
#define P180106 P180106_Sync_Start_Value
#define P0x18010x06 P180106_Sync_Start_Value
// The uppercase versions are deprecated
#define P180106_SYNC_START_VALUE P180106_Sync_Start_Value
#define PSYNC_START_VALUE_180106 P180106_Sync_Start_Value
// [5FFF,00] VisibleString
#define P5FFF00_EmSA 0x0000009D
#define PEmSA_5FFF00 P5FFF00_EmSA
#define P5FFF00 P5FFF00_EmSA
#define P0x5FFF0x00 P5FFF00_EmSA
// The uppercase versions are deprecated
#define P5FFF00_EMSA P5FFF00_EmSA
#define PEMSA_5FFF00 P5FFF00_EmSA
// [6000,00] Unsigned8
#define P600000_Number_of_Elements 0x000000C7
#define PNumber_of_Elements_600000 P600000_Number_of_Elements
#define P600000 P600000_Number_of_Elements
#define P0x60000x00 P600000_Number_of_Elements
// The uppercase versions are deprecated
#define P600000_NUMBER_OF_ELEMENTS P600000_Number_of_Elements
#define PNUMBER_OF_ELEMENTS_600000 P600000_Number_of_Elements
// [6000,05] Unsigned8
#define P600005_DigInput8_5 0x000000C8
#define PDigInput8_5_600005 P600005_DigInput8_5
#define P600005 P600005_DigInput8_5
#define P0x60000x05 P600005_DigInput8_5
// The uppercase versions are deprecated
#define P600005_DIGINPUT8_5 P600005_DigInput8_5
#define PDIGINPUT8_5_600005 P600005_DigInput8_5
// [6000,06] Unsigned8
#define P600006_DigInput8_6 0x000000C9
#define PDigInput8_6_600006 P600006_DigInput8_6
#define P600006 P600006_DigInput8_6
#define P0x60000x06 P600006_DigInput8_6
// The uppercase versions are deprecated
#define P600006_DIGINPUT8_6 P600006_DigInput8_6
#define PDIGINPUT8_6_600006 P600006_DigInput8_6
// [6000,07] Unsigned8
#define P600007_DigInput8_7 0x000000CA
#define PDigInput8_7_600007 P600007_DigInput8_7
#define P600007 P600007_DigInput8_7
#define P0x60000x07 P600007_DigInput8_7
// The uppercase versions are deprecated
#define P600007_DIGINPUT8_7 P600007_DigInput8_7
#define PDIGINPUT8_7_600007 P600007_DigInput8_7
// [6000,08] Unsigned8
#define P600008_DigInput8_8 0x000000CB
#define PDigInput8_8_600008 P600008_DigInput8_8
#define P600008 P600008_DigInput8_8
#define P0x60000x08 P600008_DigInput8_8
// The uppercase versions are deprecated
#define P600008_DIGINPUT8_8 P600008_DigInput8_8
#define PDIGINPUT8_8_600008 P600008_DigInput8_8
// [6200,00] Unsigned8
#define P620000_Number_of_Elements 0x000000CC
#define PNumber_of_Elements_620000 P620000_Number_of_Elements
#define P620000 P620000_Number_of_Elements
#define P0x62000x00 P620000_Number_of_Elements
// The uppercase versions are deprecated
#define P620000_NUMBER_OF_ELEMENTS P620000_Number_of_Elements
#define PNUMBER_OF_ELEMENTS_620000 P620000_Number_of_Elements
// [6200,05] Unsigned8
#define P620005_DigOutput8_5 0x000000CD
#define PDigOutput8_5_620005 P620005_DigOutput8_5
#define P620005 P620005_DigOutput8_5
#define P0x62000x05 P620005_DigOutput8_5
// The uppercase versions are deprecated
#define P620005_DIGOUTPUT8_5 P620005_DigOutput8_5
#define PDIGOUTPUT8_5_620005 P620005_DigOutput8_5
// [6200,06] Unsigned8
#define P620006_DigOutput8_6 0x000000CE
#define PDigOutput8_6_620006 P620006_DigOutput8_6
#define P620006 P620006_DigOutput8_6
#define P0x62000x06 P620006_DigOutput8_6
// The uppercase versions are deprecated
#define P620006_DIGOUTPUT8_6 P620006_DigOutput8_6
#define PDIGOUTPUT8_6_620006 P620006_DigOutput8_6
// [6200,07] Unsigned8
#define P620007_DigOutput8_7 0x000000CF
#define PDigOutput8_7_620007 P620007_DigOutput8_7
#define P620007 P620007_DigOutput8_7
#define P0x62000x07 P620007_DigOutput8_7
// The uppercase versions are deprecated
#define P620007_DIGOUTPUT8_7 P620007_DigOutput8_7
#define PDIGOUTPUT8_7_620007 P620007_DigOutput8_7
// [6200,08] Unsigned8
#define P620008_DigOutput8_8 0x000000D0
#define PDigOutput8_8_620008 P620008_DigOutput8_8
#define P620008 P620008_DigOutput8_8
#define P0x62000x08 P620008_DigOutput8_8
// The uppercase versions are deprecated
#define P620008_DIGOUTPUT8_8 P620008_DigOutput8_8
#define PDIGOUTPUT8_8_620008 P620008_DigOutput8_8
// [6401,00] Unsigned8
#define P640100_Number_of_Elements 0x000000D1
#define PNumber_of_Elements_640100 P640100_Number_of_Elements
#define P640100 P640100_Number_of_Elements
#define P0x64010x00 P640100_Number_of_Elements
// The uppercase versions are deprecated
#define P640100_NUMBER_OF_ELEMENTS P640100_Number_of_Elements
#define PNUMBER_OF_ELEMENTS_640100 P640100_Number_of_Elements
// [6411,00] Unsigned8
#define P641100_Number_of_Elements 0x000000D2
#define PNumber_of_Elements_641100 P641100_Number_of_Elements
#define P641100 P641100_Number_of_Elements
#define P0x64110x00 P641100_Number_of_Elements
// The uppercase versions are deprecated
#define P641100_NUMBER_OF_ELEMENTS P641100_Number_of_Elements
#define PNUMBER_OF_ELEMENTS_641100 P641100_Number_of_Elements

// last byte used in process image
#define PIMGEND 0x000000D2

// sizes for entries in the process image in bytes
#define SIZEOF_6200_01_DIGOUTPUT8_1 1
#define SIZEOF_6200_02_DIGOUTPUT8_2 1
#define SIZEOF_6200_03_DIGOUTPUT8_3 1
#define SIZEOF_6200_04_DIGOUTPUT8_4 1
#define SIZEOF_6411_01_ANALOGOUTPUT16_1 2
#define SIZEOF_6411_02_ANALOGOUTPUT16_2 2
#define SIZEOF_6000_01_VC_COMMAND 1
#define SIZEOF_6000_02_VC_ACCURACY 1
#define SIZEOF_6000_03_DIGINPUT8_3 1
#define SIZEOF_6000_04_DIGINPUT8_4 1
#define SIZEOF_6401_01_ANALOGINPUT16_1 2
#define SIZEOF_6401_02_ANALOGINPUT16_2 2
#define SIZEOF_1000_00_DEVICE_TYPE 4
#define SIZEOF_1001_00_ERROR_REGISTER 1
#define SIZEOF_1005_00_COB_ID_SYNC 4
#define SIZEOF_1006_00_SYNC_COMMUNICATION_CYCLE_TIME 4
#define SIZEOF_1008_00_MANUFACTURER_DEVICE_NAME 32
#define SIZEOF_1010_00_HIGHEST_SUBINDEX 1
#define SIZEOF_1010_01_SAVE_ALL_PARAMETERS 4
#define SIZEOF_1010_02_SAVE_COMMUNICATION_PARAMETERS 4
#define SIZEOF_1010_03_SAVE_APPLICATION_PARAMETERS 4
#define SIZEOF_1010_04_SAVE_MANUFACTURER_PARAMETERS 4
#define SIZEOF_1014_00_COB_ID_EMCY 4
#define SIZEOF_1016_01_CONSUMER_HB_TIME 4
#define SIZEOF_1016_02_CONSUMER_HB_TIME 4
#define SIZEOF_1016_03_CONSUMER_HB_TIME 4
#define SIZEOF_1016_04_CONSUMER_HB_TIME 4
#define SIZEOF_1016_05_CONSUMER_HB_TIME 4
#define SIZEOF_1016_06_CONSUMER_HB_TIME 4
#define SIZEOF_1016_07_CONSUMER_HB_TIME 4
#define SIZEOF_1016_08_CONSUMER_HB_TIME 4
#define SIZEOF_1016_09_CONSUMER_HB_TIME 4
#define SIZEOF_1016_0A_CONSUMER_HB_TIME 4
#define SIZEOF_1017_00_PRODUCER_HEARTBEAT_TIME 2
#define SIZEOF_1019_00_SYNC_COUNTER_OVERFLOW_VALUE 1
#define SIZEOF_1400_00_HIGHEST_SUBINDEX 1
#define SIZEOF_1400_01_COB_ID 4
#define SIZEOF_1400_02_TRANSMISSION_TYPE 1
#define SIZEOF_1401_00_HIGHEST_SUBINDEX 1
#define SIZEOF_1401_01_COB_ID 4
#define SIZEOF_1401_02_TRANSMISSION_TYPE 1
#define SIZEOF_1800_01_COB_ID 4
#define SIZEOF_1800_02_TRANSMISSION_TYPE 1
#define SIZEOF_1800_03_INHIBIT_TIME 2
#define SIZEOF_1800_05_EVENT_TIMER 2
#define SIZEOF_1800_06_SYNC_START_VALUE 1
#define SIZEOF_1801_01_COB_ID 4
#define SIZEOF_1801_02_TRANSMISSION_TYPE 1
#define SIZEOF_1801_03_INHIBIT_TIME 2
#define SIZEOF_1801_05_EVENT_TIMER 2
#define SIZEOF_1801_06_SYNC_START_VALUE 1
#define SIZEOF_5FFF_00_EMSA 42
#define SIZEOF_6000_00_NUMBER_OF_ELEMENTS 1
#define SIZEOF_6000_05_DIGINPUT8_5 1
#define SIZEOF_6000_06_DIGINPUT8_6 1
#define SIZEOF_6000_07_DIGINPUT8_7 1
#define SIZEOF_6000_08_DIGINPUT8_8 1
#define SIZEOF_6200_00_NUMBER_OF_ELEMENTS 1
#define SIZEOF_6200_05_DIGOUTPUT8_5 1
#define SIZEOF_6200_06_DIGOUTPUT8_6 1
#define SIZEOF_6200_07_DIGOUTPUT8_7 1
#define SIZEOF_6200_08_DIGOUTPUT8_8 1
#define SIZEOF_6401_00_NUMBER_OF_ELEMENTS 1
#define SIZEOF_6411_00_NUMBER_OF_ELEMENTS 1

// default values for process image
#define PIMGDEFAULTS { \
/*[6200,01]*/        0x00, \
/*[6200,02]*/        0x00, \
/*[6200,03]*/        0x00, \
/*[6200,04]*/        0x00, \
/*[6411,01]*/        0x00, 0x00, \
/*[6411,02]*/        0x00, 0x00, \
/*[6000,01]*/        0x00, \
/*[6000,02]*/        0x00, \
/*[6000,03]*/        0x00, \
/*[6000,04]*/        0x00, \
/*[6401,01]*/        0x00, 0x00, \
/*[6401,02]*/        0x00, 0x00, \
/*[1000,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1001,00]*/        0x00, \
/*[1005,00]*/        0x80, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x43, 0x41, 0x4E, 0x6F, 0x70, 0x65, 0x6E, 0x4C, 0x69, 0x62, \
                     0x4E, 0x58, 0x50, 0x53, 0x44, 0x4B, 0x20, 0x4D, 0x61, 0x6E, \
                     0x61, 0x67, 0x65, 0x72, 0x20, 0x45, 0x78, 0x61, 0x6D, 0x70, \
                     0x6C, 0x65, \
/*[1010,00]*/        0x04, \
/*[1010,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1014,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,01]*/        0xCA, 0x08, 0x01, 0x00, \
/*[1016,02]*/        0xCA, 0x08, 0x02, 0x00, \
/*[1016,03]*/        0xCA, 0x08, 0x03, 0x00, \
/*[1016,04]*/        0xCA, 0x08, 0x04, 0x00, \
/*[1016,05]*/        0xCA, 0x08, 0x05, 0x00, \
/*[1016,06]*/        0xCA, 0x08, 0x06, 0x00, \
/*[1016,07]*/        0xCA, 0x08, 0x07, 0x00, \
/*[1016,08]*/        0xCA, 0x08, 0x08, 0x00, \
/*[1016,09]*/        0xCA, 0x08, 0x09, 0x00, \
/*[1016,0A]*/        0xCA, 0x08, 0x0A, 0x00, \
/*[1017,00]*/        0x4D, 0x01, \
/*[1019,00]*/        0x00, \
/*[1400,00]*/        0x02, \
/*[1400,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1400,02]*/        0xFF, \
/*[1401,00]*/        0x02, \
/*[1401,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1401,02]*/        0xFF, \
/*[1800,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1800,02]*/        0xFF, \
/*[1800,03]*/        0xE8, 0x03, \
/*[1800,05]*/        0xF4, 0x01, \
/*[1800,06]*/        0x00, \
/*[1801,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1801,02]*/        0xFF, \
/*[1801,03]*/        0xC4, 0x09, \
/*[1801,05]*/        0xE8, 0x03, \
/*[1801,06]*/        0x00, \
/*[5FFF,00]*/        0x45, 0x6D, 0x53, 0x41, 0x20, 0x77, 0x77, 0x77, 0x2E, 0x65, \
                     0x6D, 0x2D, 0x73, 0x61, 0x2E, 0x63, 0x6F, 0x6D, 0x2C, 0x20, \
                     0x43, 0x41, 0x4E, 0x6F, 0x70, 0x65, 0x6E, 0x20, 0x41, 0x72, \
                     0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x20, 0x4D, 0x69, \
                     0x6E, 0x69, \
/*[6000,00]*/        0x08, \
/*[6000,05]*/        0x00, \
/*[6000,06]*/        0x00, \
/*[6000,07]*/        0x00, \
/*[6000,08]*/        0x00, \
/*[6200,00]*/        0x08, \
/*[6200,05]*/        0x00, \
/*[6200,06]*/        0x00, \
/*[6200,07]*/        0x00, \
/*[6200,08]*/        0x00, \
/*[6401,00]*/        0x02, \
/*[6411,00]*/        0x02, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGDEFAULTS 

// minimum values for process image
#define PIMGMINS { \
/*[6200,01]*/        0x00, \
/*[6200,02]*/        0x00, \
/*[6200,03]*/        0x00, \
/*[6200,04]*/        0x00, \
/*[6411,01]*/        0x00, 0x00, \
/*[6411,02]*/        0x00, 0x00, \
/*[6000,01]*/        0x00, \
/*[6000,02]*/        0x00, \
/*[6000,03]*/        0x00, \
/*[6000,04]*/        0x00, \
/*[6401,01]*/        0x00, 0x00, \
/*[6401,02]*/        0x00, 0x00, \
/*[1000,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1001,00]*/        0x00, \
/*[1005,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,00]*/        0x00, \
/*[1010,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1014,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,05]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,06]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,07]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,08]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,09]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,0A]*/        0x00, 0x00, 0x00, 0x00, \
/*[1017,00]*/        0x00, 0x00, \
/*[1019,00]*/        0x00, \
/*[1400,00]*/        0x00, \
/*[1400,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1400,02]*/        0x00, \
/*[1401,00]*/        0x00, \
/*[1401,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1401,02]*/        0x00, \
/*[1800,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1800,02]*/        0x00, \
/*[1800,03]*/        0x00, 0x00, \
/*[1800,05]*/        0x00, 0x00, \
/*[1800,06]*/        0x00, \
/*[1801,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1801,02]*/        0x00, \
/*[1801,03]*/        0x00, 0x00, \
/*[1801,05]*/        0x00, 0x00, \
/*[1801,06]*/        0x00, \
/*[5FFF,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6000,00]*/        0x00, \
/*[6000,05]*/        0x00, \
/*[6000,06]*/        0x00, \
/*[6000,07]*/        0x00, \
/*[6000,08]*/        0x00, \
/*[6200,00]*/        0x00, \
/*[6200,05]*/        0x00, \
/*[6200,06]*/        0x00, \
/*[6200,07]*/        0x00, \
/*[6200,08]*/        0x00, \
/*[6401,00]*/        0x00, \
/*[6411,00]*/        0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMINS 

// maximum values for process image
#define PIMGMAXS { \
/*[6200,01]*/        0x00, \
/*[6200,02]*/        0x00, \
/*[6200,03]*/        0x00, \
/*[6200,04]*/        0x00, \
/*[6411,01]*/        0x00, 0x00, \
/*[6411,02]*/        0x00, 0x00, \
/*[6000,01]*/        0x00, \
/*[6000,02]*/        0x00, \
/*[6000,03]*/        0x00, \
/*[6000,04]*/        0x00, \
/*[6401,01]*/        0x00, 0x00, \
/*[6401,02]*/        0x00, 0x00, \
/*[1000,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1001,00]*/        0x00, \
/*[1005,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1006,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1008,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,00]*/        0x00, \
/*[1010,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1010,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1014,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,01]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,02]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,03]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,04]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,05]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,06]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,07]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,08]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,09]*/        0x00, 0x00, 0x00, 0x00, \
/*[1016,0A]*/        0x00, 0x00, 0x00, 0x00, \
/*[1017,00]*/        0x00, 0x00, \
/*[1019,00]*/        0x00, \
/*[1400,00]*/        0x00, \
/*[1400,01]*/        0xFF, 0xFF, 0xFF, 0xFF, \
/*[1400,02]*/        0x00, \
/*[1401,00]*/        0x00, \
/*[1401,01]*/        0xFF, 0xFF, 0xFF, 0xFF, \
/*[1401,02]*/        0x00, \
/*[1800,01]*/        0xFF, 0xFF, 0xFF, 0xFF, \
/*[1800,02]*/        0x00, \
/*[1800,03]*/        0x00, 0x00, \
/*[1800,05]*/        0x00, 0x00, \
/*[1800,06]*/        0x00, \
/*[1801,01]*/        0xFF, 0xFF, 0xFF, 0xFF, \
/*[1801,02]*/        0x00, \
/*[1801,03]*/        0x00, 0x00, \
/*[1801,05]*/        0x00, 0x00, \
/*[1801,06]*/        0x00, \
/*[5FFF,00]*/        0x00, 0x00, 0x00, 0x00, \
/*[6000,00]*/        0x00, \
/*[6000,05]*/        0x00, \
/*[6000,06]*/        0x00, \
/*[6000,07]*/        0x00, \
/*[6000,08]*/        0x00, \
/*[6200,00]*/        0x00, \
/*[6200,05]*/        0x00, \
/*[6200,06]*/        0x00, \
/*[6200,07]*/        0x00, \
/*[6200,08]*/        0x00, \
/*[6401,00]*/        0x00, \
/*[6411,00]*/        0x00, \
                     }

// 1 MACROS WERE GENERATED TO HOLD THE PROCESS IMAGE
// USE THE FOLLOWING INITIALIZER:
// PIMGMAXS 

// Example usage: PIMG_OFFSET(0x1000, 0x00)
#define PIMG_OFFSET(index, subindex) P##index##subindex

#endif // _PIMGH_
